# Generated by Django 5.0.2 on 2024-09-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progect',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
