# Generated by Django 5.0.2 on 2024-09-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_progect_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progect',
            name='uddata_at',
        ),
        migrations.AddField(
            model_name='progect',
            name='updata_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
